import Head from "next/head";
import Button from "~/components/button";
import TextReveal from "~/components/text-reveal";
import { GitHubLogoIcon } from "@radix-ui/react-icons";
import { useSession } from "next-auth/react"
import Link from "next/link";


export default function Home() {

  const { data: session, status } = useSession();

  return (
    <>
      <Head>
        <title>Hokagi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-white">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-default sm:text-[5rem] font-inter">
            Meet <span className="text-primary font-inter">Hokagi</span>
          </h1>
          <TextReveal text="Guiding you towards seamless automation in product and marketing event creation and QA" />
          <Button>
            <div className="flex space-x-2 items-center">
              <Link href='/api/auth/signin'>Sign In</Link>
              <GitHubLogoIcon className="size-5" />
            </div>
          </Button>
        </div>
      </main>
    </>
  );
}
